import Link from "next/link"
import Image from "next/image"
import { bhkConfigs } from "@/data/bhk"
import { serviceConfigs } from "@/data/services-v2"
import { buildMetadata } from "@/lib/seo-v2"
import { formatRange } from "@/lib/format"
import { localBusinessSchema } from "@/lib/schema"
import { StructuredData } from "@/components/seo/structured-data"
import { CtaBanner, HeroStats } from "@/components/content/page-sections"
import { GoogleReviews } from "@/components/content/google-reviews"
import { getGoogleReviews } from "@/lib/google-reviews"
import BeforeAfterSlider from "@/components/content/before-after-slider"
import { siteConfig } from "@/config/site"
import { buildWhatsAppLink } from "@/lib/whatsapp"
export const metadata = buildMetadata({ seo: { title: "Interior Designers in Ghaziabad, Noida & Greater Noida", description: "Walls N Interior publishes clear home-interior price ranges for Ghaziabad, Noida and Greater Noida. Compare 2BHK, 3BHK and 4BHK options.", primaryKeyword: "interior designers in ghaziabad" }, path: "/" })
const homeProjects = [
  { href: "/projects/contemporary-family-home", image: "/images/projects/contemporary-family-home/04.webp", alt: "Warm contemporary living room in a completed family home", tag: "Photo story · 36 images", title: "Contemporary Family Home", blurb: "A complete apartment interior balancing warm neutrals, practical storage and individual bedroom personalities.", cta: "Explore the home" },
  { href: "/projects/shrishti-interior-work", image: "/images/projects/shrishti-interior-work-poster.jpg", alt: "Shrishti completed interior walkthrough preview", tag: "Video walkthrough · 24 sec", title: "Shrishti Interior", blurb: "A candid walkthrough showing the completed finishes, fitted furniture and room-to-room flow.", cta: "Watch the walkthrough" },
  { href: "/projects/gaur-saundaryam", image: "/images/projects/gaur-saundaryam-poster.jpg", alt: "Gaur Saundaryam completed interior walkthrough preview", tag: "Video walkthrough · 38 sec", title: "Gaur Saundaryam", blurb: "A completed-home walkthrough featuring elegant wall details, bespoke storage and warm lighting.", cta: "Watch the walkthrough" },
]
export default async function HomePage() {
  const reviews = await getGoogleReviews()
  return <><StructuredData data={localBusinessSchema(undefined, reviews)} /><main>
  <section className="home-hero"><div><p className="eyebrow">Ghaziabad · Noida · Greater Noida</p><h1>Beautiful interiors.<br />Prices you can see.</h1><p className="lead">Full-home design and execution with published indicative ranges, clear inclusions and an itemised path from measurement to handover.</p><div className="button-row"><Link className="button button-primary" href="#interiors">See home prices</Link><Link className="button button-secondary" href="/tools/cost-calculator">Estimate my cost</Link></div><HeroStats reviews={reviews} /><div className="hero-proof"><span>Estimated prices shown before enquiry</span><a data-cta="hero-whatsapp" href={buildWhatsAppLink({ number: siteConfig.whatsapp, text: "Hi Walls N Interior, I'd like a one-tap estimate for my home interiors." })} target="_blank" rel="noreferrer">One-tap WhatsApp</a></div></div><BeforeAfterSlider /></section>
  <section className="content-section"><div className="section-heading"><p className="eyebrow">Recent work</p><h2>Real homes we&rsquo;ve finished</h2><p>Photo stories and on-site walkthroughs from completed Walls N Interior projects.</p></div><div className="card-grid">{homeProjects.map(p => <Link className="project-feature-card" href={p.href} key={p.href}><div className="project-card-media"><Image src={p.image} alt={p.alt} fill sizes="(max-width:640px) 100vw,(max-width:960px) 50vw,33vw" /></div><div className="project-card-copy"><div><p className="eyebrow">{p.tag}</p><h3>{p.title}</h3><p>{p.blurb}</p></div><span className="text-link">{p.cta} →</span></div></Link>)}</div><div className="section-cta"><Link className="button button-secondary" href="/projects">See all projects</Link></div></section>
  <GoogleReviews data={reviews} />
  <section className="content-section" id="interiors"><div className="section-heading"><p className="eyebrow">Start with your floor plan</p><h2>Full-home interior price ranges</h2><p>Benchmark the whole project before comparing finishes and modules.</p></div><div className="bhk-grid">{bhkConfigs.map(item => <Link className="bhk-card" href={`/interiors/${item.slug}`} key={item.slug}><div><p className="eyebrow">{item.timeline.weeks.min}–{item.timeline.weeks.max} week plan</p><h3>{item.label}</h3><p>{item.bedrooms} bedrooms · {item.bathrooms} bathrooms</p></div><div><p className="tier-price">{formatRange(item.headlinePrice)}</p><p className="price-note">Indicative range</p></div><span className="text-link">Compare all three tiers →</span></Link>)}</div></section>
  <section className="content-section tint"><div className="section-heading"><p className="eyebrow">Individual modules</p><h2>Build only what you need</h2></div><div className="card-grid">{serviceConfigs.map(item => <Link className="info-card link-card" href={`/services/${item.slug}`} key={item.slug}><h3>{item.name}</h3><p>{item.intro}</p><p className="tier-price">{formatRange(item.headlinePrice)}</p><span className="text-link">View scope →</span></Link>)}</div></section>
  <section className="content-section split"><div><p className="eyebrow">Why this site is different</p><h2>No quote wall between you and the price</h2><p className="lead">Most interior firms make you surrender your phone number before showing a number. Here, the estimate comes first. You contact us only when the scope makes sense.</p><Link className="button button-primary" href="/cost">Browse cost guides</Link></div><div className="principles"><article><strong>01</strong><h3>Published ranges</h3><p>See a realistic starting point before a sales conversation.</p></article><article><strong>02</strong><h3>Clear exclusions</h3><p>Understand what is outside each package and avoid surprise add-ons.</p></article><article><strong>03</strong><h3>Local coordination</h3><p>Meet at our Crossings Republik studio and plan around your actual site.</p></article></div></section>
  <CtaBanner heading="Send your floor plan. Get a clearer number." subheading="No obligation and no hidden estimate gate." />
  </main></> }
