import { fullAddress, siteConfig } from "@/config/site"
import type { Faq, PriceRange } from "@/types/content"
import { canonical } from "@/lib/seo-v2"

export const organizationSchema = () => ({ "@context": "https://schema.org", "@type": "Organization", "@id": `${siteConfig.url}/#organization`, name: siteConfig.name, url: siteConfig.url, email: siteConfig.email, telephone: siteConfig.phone })
export const websiteSchema = () => ({ "@context": "https://schema.org", "@type": "WebSite", "@id": `${siteConfig.url}/#website`, name: siteConfig.name, url: siteConfig.url, inLanguage: siteConfig.locale })
export const localBusinessSchema = (areaServed = siteConfig.areas) => ({ "@context": "https://schema.org", "@type": "HomeAndConstructionBusiness", "@id": `${siteConfig.url}/#business`, name: siteConfig.name, url: siteConfig.url, telephone: siteConfig.phone, email: siteConfig.email, priceRange: siteConfig.priceRange, address: { "@type": "PostalAddress", streetAddress: siteConfig.address.street, addressLocality: siteConfig.address.city, addressRegion: siteConfig.address.region, postalCode: siteConfig.address.postalCode, addressCountry: siteConfig.address.country }, openingHoursSpecification: siteConfig.hours.map(h => ({ "@type": "OpeningHoursSpecification", dayOfWeek: h.days, opens: h.opens, closes: h.closes })), areaServed: areaServed.map(name => ({ "@type": "City", name })) })
export const breadcrumbsSchema = (items: { label: string; href?: string }[]) => ({ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: items.map((item, index) => ({ "@type": "ListItem", position: index + 1, name: item.label, item: item.href ? canonical(item.href) : undefined })) })
export const faqSchema = (faqs: Faq[]) => ({ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(faq => ({ "@type": "Question", name: faq.q, acceptedAnswer: { "@type": "Answer", text: faq.a } })) })
export const serviceSchema = (name: string, description: string, path: string, range: PriceRange) => ({ "@context": "https://schema.org", "@type": "Service", name, description, url: canonical(path), provider: { "@id": `${siteConfig.url}/#business` }, areaServed: siteConfig.areas, offers: { "@type": "Offer", priceCurrency: "INR", priceSpecification: { "@type": "PriceSpecification", minPrice: range.min, maxPrice: range.max, priceCurrency: "INR" } } })
export const articleSchema = (headline: string, description: string, path: string, updatedAt: string) => ({ "@context": "https://schema.org", "@type": "Article", headline, description, mainEntityOfPage: canonical(path), datePublished: updatedAt, dateModified: updatedAt, author: { "@type": "Organization", name: siteConfig.name }, publisher: { "@id": `${siteConfig.url}/#organization` } })
