import { LayoutImagePreview } from "@/components/content/layout-image-preview"

const falseCeilingTypes = [
  { name: "Single-level false ceiling", image: "/images/false-ceiling-layouts/single-level-false-ceiling.jpg", width: 736, height: 1104, alt: "Minimal single-level false ceiling with geometric linear lights", bestFor: "Standard-height rooms and clean, minimal interiors", description: "A single dropped plane neatly conceals wiring and accommodates spotlights or linear lighting while limiting the loss of ceiling height." },
  { name: "Double-layer false ceiling", image: "/images/false-ceiling-layouts/double-layer-false-ceiling.jpg", width: 735, height: 503, alt: "Double-layer false ceiling with rounded corners and warm cove lighting", bestFor: "Larger rooms that benefit from depth and layered lighting", description: "Two ceiling levels create visual depth and make it easier to combine ambient cove light with focused task lighting. Adequate ceiling height is essential." },
  { name: "Gypsum ceiling with spotlights", image: "/images/false-ceiling-layouts/gypsum-ceiling-with-spotlights.png", width: 1152, height: 2048, alt: "Modern gypsum tray ceiling with spotlights above a dining area", bestFor: "Modern homes needing practical lighting zones", description: "Smooth gypsum boards form crisp edges and integrate recessed spotlights, linear profiles and cove lighting. Electrical access should be planned before closing the ceiling." },
  { name: "Gypsum and wooden ceiling", image: "/images/false-ceiling-layouts/combination-gypsum-wooden-ceiling.jpg", width: 735, height: 490, alt: "White gypsum false ceiling with a wooden tray border and ceiling fan", bestFor: "Contemporary rooms that need warmth and material contrast", description: "A gypsum base keeps the ceiling bright while wooden bands or insets introduce warmth. The timber finish can coordinate with furniture, doors and wall panelling." },
  { name: "Wooden or fluted ceiling", image: "/images/false-ceiling-layouts/wooden-fluted-ceiling.jpg", width: 736, height: 1104, alt: "Warm wooden inset ceiling with a cluster of pendant lights", bestFor: "Dining and living spaces needing warmth and texture", description: "Wood, veneer or fluted panels make the ceiling a rich focal surface and can improve perceived acoustics. Moisture, fire safety and lighting access need careful detailing." },
  { name: "Curved or wave ceiling", image: "/images/false-ceiling-layouts/curved-wave-ceiling.jpg", width: 735, height: 1103, alt: "Flowing curved false ceiling with warm concealed lighting", bestFor: "Open-plan contemporary interiors with soft forms", description: "Flowing profiles soften straight room geometry and guide the eye between zones. Precise framing and skilled finishing are important for smooth, consistent curves." },
  { name: "Geometric false ceiling", image: "/images/false-ceiling-layouts/geometric-false-ceiling.jpg", width: 736, height: 1313, alt: "Geometric false ceiling with illuminated irregular panels", bestFor: "Feature-led living rooms and bold contemporary schemes", description: "Repeated polygons, lines or asymmetrical forms create a strong focal point. The composition works best when aligned with the room, furniture and lighting plan." },
  { name: "Coffered ceiling", image: "/images/false-ceiling-layouts/coffered-ceiling.jpg", width: 688, height: 1024, alt: "Classic white coffered ceiling in a formal living room", bestFor: "High ceilings and spacious classic or transitional rooms", description: "A grid of recessed panels adds architectural rhythm and grandeur. Coffers can be kept minimal or detailed with mouldings, spotlights and contrasting finishes." },
  { name: "Ceiling with chandelier feature", image: "/images/false-ceiling-layouts/chandelier-feature-ceiling.jpg", width: 736, height: 1104, alt: "Layered rectangular false ceiling centred around a crystal chandelier", bestFor: "Dining rooms, formal living areas and entrance foyers", description: "A centred recess or layered frame gives a chandelier a deliberate architectural setting. Fixture scale, structural support and maintenance access must be resolved early." },
  { name: "POP decorative ceiling", image: "/images/false-ceiling-layouts/pop-decorative-ceiling.jpg", width: 513, height: 640, alt: "Decorative POP false ceiling with rounded moulded profiles under construction", bestFor: "Custom curves, borders and detailed on-site profiles", description: "Plaster of Paris can form sculpted borders, mouldings and smooth decorative shapes. The finish depends heavily on workmanship, drying time and crack-resistant detailing." },
] as const

export default function FalseCeilingLayouts() {
  return <section className="content-section tv-unit-layout-section"><div className="section-heading"><p className="eyebrow">Plan ceiling and lighting together</p><h2>Popular false-ceiling designs</h2><p>Ceiling height, room size, lighting requirements and the desired visual effect determine the right design. Compare these options before finalising levels, materials and electrical points.</p></div><div className="tv-unit-layout-grid">{falseCeilingTypes.map(ceiling => <div className="layout-card-trigger" key={ceiling.name}><article className="tv-unit-layout-card"><LayoutImagePreview className="tv-unit-layout-image" src={ceiling.image} alt={ceiling.alt} width={ceiling.width} height={ceiling.height} /><div className="tv-unit-layout-copy"><h3>{ceiling.name}</h3><p className="tv-unit-layout-best"><strong>Best for:</strong> {ceiling.bestFor}</p><p>{ceiling.description}</p></div></article></div>)}</div><p className="small tv-unit-layout-note">The final design is confirmed after measuring the slab height and checking beams, fans, light points, air-conditioning, fire services and maintenance access.</p></section>
}
