import Link from "next/link"
import { notFound } from "next/navigation"
import { serviceConfigs } from "@/data/services-v2"
import { buildMetadata } from "@/lib/seo-v2"
import { breadcrumbsSchema, faqSchema, serviceSchema } from "@/lib/schema"
import { StructuredData } from "@/components/seo/structured-data"
import { Breadcrumbs, CtaBanner, FaqList, PlaceholderImage, ThreeDDesignSection } from "@/components/content/page-sections"
import { PriceHero } from "@/components/content/pricing"
export function generateStaticParams() { return serviceConfigs.map(item => ({ service: item.slug })) }
export async function generateMetadata({ params }: { params: Promise<{ service: string }> }) { const { service } = await params; const item = serviceConfigs.find(x => x.slug === service); return item ? buildMetadata({ seo: item.seo, path: `/services/${item.slug}` }) : {} }
export default async function ServicePage({ params }: { params: Promise<{ service: string }> }) { const { service } = await params; const item = serviceConfigs.find(x => x.slug === service); if (!item) notFound(); const crumbs = [{ label: "Home", href: "/" }, { label: "Services", href: "/services" }, { label: item.name }]; return <><StructuredData data={[serviceSchema(item.name, item.intro, `/services/${item.slug}`, item.headlinePrice), faqSchema(item.faqs), breadcrumbsSchema(crumbs)]} /><article><div className="page-hero"><div className="container-narrow"><Breadcrumbs items={crumbs} /><p className="eyebrow">Transparent module pricing</p><h1>{item.h1}</h1><p className="lead">{item.intro}</p></div><PriceHero range={item.headlinePrice} label="Indicative range" /></div><section className="content-section split"><div><p className="eyebrow">Material choices</p><h2>Know what you are buying</h2>{item.materials.map(material => <article className="material-row" key={material.name}><div><h3>{material.name}</h3><span className="badge">{material.category}</span></div><div><p><strong>Why choose it:</strong> {material.pros.join(" · ")}</p><p className="small"><strong>Trade-off:</strong> {material.cons.join(" · ")}</p></div></article>)}</div><PlaceholderImage label={`Real ${item.name.toLowerCase()} project photography required`} /></section><section className="content-section tint"><p className="eyebrow">From measure to installation</p><h2 className="process-heading">A clear three-step process</h2><div className="card-grid">{item.process.map(step => <article className="info-card" key={step.step}><span className="step-number">0{step.step}</span><h3>{step.title}</h3><p>{step.detail}</p></article>)}</div></section><ThreeDDesignSection /><section className="content-section split"><div><h2>Frequently asked questions</h2><FaqList faqs={item.faqs} /></div><div><h2>Plan it as part of a full home</h2><div className="link-stack">{item.relatedBhk.map(slug => { const bhk = slug.split("-")[0].toUpperCase(); return <Link className="info-card link-card" href={`/interiors/${slug}`} key={slug}>{bhk} interior pricing <span>→</span></Link> })}</div></div></section><CtaBanner heading={item.cta.heading} /></article></> }
