"use client"
import { useMemo, useState } from "react"
import Link from "next/link"
import { formatINR } from "@/lib/format"
import { siteConfig } from "@/config/site"
import WhatsAppIcon from "@/components/site/whatsapp-icon"

const base = { "2 BHK": [250000, 1200000], "3 BHK": [450000, 1800000], "4 BHK": [900000, 3000000] } as const
const factors = { Essential: .72, Comfort: 1, Premium: 1.42 } as const
export default function CostCalculator() {
  const [bhk, setBhk] = useState<keyof typeof base>("3 BHK"); const [area, setArea] = useState(1250); const [tier, setTier] = useState<keyof typeof factors>("Comfort"); const [scope, setScope] = useState("Full home");
  const estimate = useMemo(() => { const b = base[bhk]; const areaFactor = Math.max(.75, Math.min(1.35, area / ({ "2 BHK": 850, "3 BHK": 1300, "4 BHK": 2000 }[bhk]))); const scopeFactor = scope === "Full home" ? 1 : scope === "Kitchen + wardrobes" ? .55 : .25; return [Math.round(b[0] * factors[tier] * areaFactor * scopeFactor / 10000) * 10000, Math.round(b[1] * factors[tier] * areaFactor * scopeFactor / 10000) * 10000] }
  ,[bhk, area, tier, scope]); const message = encodeURIComponent(`Hi Walls N Interior, my website estimate is ${formatINR(estimate[0])}–${formatINR(estimate[1])} for a ${bhk}, ${area} sq ft, ${tier}, ${scope.toLowerCase()} project.`)
  return <div className="calculator"><div className="calculator-fields"><fieldset><legend>1. Property</legend><div className="choice-row">{Object.keys(base).map(v => <button className={bhk === v ? "active" : ""} onClick={() => setBhk(v as keyof typeof base)} type="button" key={v}>{v}</button>)}</div></fieldset><fieldset><legend>2. Carpet area: <strong>{area.toLocaleString("en-IN")} sq ft</strong></legend><input type="range" min="400" max="3000" step="50" value={area} onChange={e => setArea(Number(e.target.value))} /></fieldset><fieldset><legend>3. Scope</legend><div className="choice-row">{["Full home", "Kitchen + wardrobes", "Kitchen only"].map(v => <button className={scope === v ? "active" : ""} onClick={() => setScope(v)} type="button" key={v}>{v}</button>)}</div></fieldset><fieldset><legend>4. Finish</legend><div className="choice-row">{Object.keys(factors).map(v => <button className={tier === v ? "active" : ""} onClick={() => setTier(v as keyof typeof factors)} type="button" key={v}>{v}</button>)}</div></fieldset></div><aside className="calculator-result"><p className="eyebrow light">Your indicative estimate</p><p className="price-display">{formatINR(estimate[0], true)} – {formatINR(estimate[1], true)}</p><p>Shown before we ask for your phone number. Final pricing needs site measurement and an itemised scope.</p><ul><li>Includes design and selected modular scope</li><li>Excludes civil work, appliances and loose furniture</li><li>Uses unverified August 2026 market benchmarks</li></ul><a className="button button-whatsapp" href={`https://wa.me/${siteConfig.whatsapp}?text=${message}`} target="_blank" rel="noreferrer"><WhatsAppIcon />WhatsApp this estimate</a><Link className="button button-light" href="/contact">Request site measurement</Link></aside></div>
}
